package:
  name: openforcefield
  version: 0.0.0

source:
  path: ../..

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - networkx
    - parmed
    - rdkit
    - ambermini
    - packaging
    # Should we require this? It's useful for tests and examples, but not strictly required
    - openmmtools
    # Serialization: Should these be optional?
    - pyyaml
    - toml
    - bson
    - msgpack-python
    - xmltodict

about:
  home: https://github.com/openforcefield/openforcefield
  license: MIT
